version: '3'

services:
  www:
    env_file:
      - .env.local
    build:
      context: ..
      dockerfile: Dockerfile
      target: pockethost-base
    platform: linux/amd64
    container_name: www
    restart: unless-stopped
    working_dir: /src
    command: bash -c "yarn dev:www --host=www"
    volumes:
      - ..:/src
      - ./mount/cache/node_modules:/src/node_modules
    networks:
      - app-network
    ports:
      - '9000:5173'
    depends_on:
      daemon:
        condition: service_started
  daemon:
    env_file:
      - .env.local
    build:
      context: ..
      dockerfile: Dockerfile
      target: pockethost-base
    platform: linux/amd64
    container_name: daemon
    working_dir: /src
    command: bash -c "yarn dev:daemon"
    restart: unless-stopped
    volumes:
      - ..:/src
      - ./mount/cache/yarn:/yarn-cache
      - ./mount/cache/go-mod:/go-mod
      - ./mount/cache/go-cache:/go-cache
      - ./mount/cache/node_modules:/src/node_modules
      - ./mount/daemon/instances:/data
    networks:
      - app-network
    ports:
      - '9001:3000'
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - www
      - daemon
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./mount/nginx/conf.d/local:/etc/nginx/conf.d
      - ./mount/nginx/logs:/mount/nginx/logs
      - ./mount/nginx/ssl:/mount/nginx/ssl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
