version: '3'

services:
  prepbox:
    env_file:
      - .env.local
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: prepbox
    working_dir: /src
    command: bash -c "yarn"
    volumes:
      - ..:/src
      - ./mount/cache/yarn:/yarn-cache
      - ./mount/cache/go-mod:/go-mod
      - ./mount/cache/go-cache:/go-cache
      - ./mount/cache/node_modules:/src/node_modules
