version: '3'

services:
  www:
    env_file:
      - .env.local
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: www
    restart: unless-stopped
    working_dir: /src
    command: bash -c "yarn && yarn dev:www --host=www"
    volumes:
      - ../package.json:/src/package.json
      - ../yarn.lock:/src/yarn.lock
      - ../packages/pockethost.io/src:/src/packages/pockethost.io/src
      - ../packages/pockethost.io/package.json:/src/packages/pockethost.io/package.json
      - ../packages/pockethost.io/yarn.lock:/src/packages/pockethost.io/yarn.lock
      - ../packages/common/src:/src/packages/common/src
      - ../packages/common/package.json:/src/packages/common/package.json
    networks:
      - app-network
    ports:
      - '9000:5173'
    depends_on:
      - daemon
  daemon:
    env_file:
      - .env.local
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: daemon
    working_dir: /src
    command: bash -c "yarn && yarn dev:daemon"
    restart: unless-stopped
    environment:
      - SHELL=/bin/bash
    volumes:
      - ../package.json:/src/package.json
      - ../yarn.lock:/src/yarn.lock
      - ./mount/daemon/instances:/data
      - ../packages/common/src:/src/packages/common/src
      - ../packages/common/package.json:/src/packages/common/package.json
      - ../packages/daemon/src:/src/packages/daemon/src
      - ../packages/daemon/package.json:/src/packages/daemon/package.json
      - ../packages/daemon/yarn.lock:/src/packages/daemon/yarn.lock
    networks:
      - app-network
    ports:
      - '9001:3000'
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - www
      - daemon
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./mount/nginx/conf.d/local:/etc/nginx/conf.d
      - ./mount/nginx/logs:/mount/logs
      - ./mount/nginx/ssl:/mount/ssl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
