version: '3'

services:
  prepbox:
    env_file:
      - .env.local
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: prepbox
    working_dir: /src
    command: bash -c "pnpm migrate"
    volumes:
      - ./mount/daemon/instances:/data
      - ./mount/cache/go:/go
      - ./mount/cache/pnpm:/src/docker/mount/cache/pnpm
      - ..:/src
