version: '3'

services:
  www:
    env_file:
      - .env.local
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: www
    restart: unless-stopped
    working_dir: /src
    command: bash -c "pnpm start:www --host=www"
    volumes:
      - ..:/src
    networks:
      - app-network
    ports:
      - '9000:5173'
    depends_on:
      daemon:
        condition: service_started
  daemon:
    env_file:
      - .env.local
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: daemon
    working_dir: /src
    command: bash -c "pnpm start:daemon"
    restart: unless-stopped
    environment:
      - SHELL=/bin/bash
    volumes:
      - /home/pockethost/data:/data
      - ..:/src
    networks:
      - app-network
    ports:
      - '9001:3000'
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - www
      - daemon
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./mount/nginx/conf.d/prod:/etc/nginx/conf.d
      - ./mount/nginx/logs:/mount/nginx/logs
      - ./mount/nginx/ssl:/mount/nginx/ssl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
