version: '3'
services:
  www:
    image: benallfree/pockethost
    env_file:
      - .env.local
    platform: linux/amd64
    container_name: www
    restart: unless-stopped
    working_dir: /pockethost/www
    command: node index.js --host=www
    networks:
      - app-network
    ports:
      - '9000:5173'
    depends_on:
      daemon:
        condition: service_started
  daemon:
    image: benallfree/pockethost
    env_file:
      - .env.local
    platform: linux/amd64
    container_name: daemon
    working_dir: /pockethost/daemon/packages/daemon
    command: yarn start
    restart: unless-stopped
    environment:
      - SHELL=/bin/bash
    volumes:
      - '${PH_DATA:?PH_DATA Required}:/data'
    networks:
      - app-network
    ports:
      - '9001:3000'
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - www
      - daemon
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '${PH_NGINX:?PH_NGINX required}/conf.d/prod:/etc/nginx/conf.d'
      - '${PH_NGINX}/logs:/mount/nginx/logs'
      - '${PH_NGINX}/ssl:/mount/nginx/ssl'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
